module.exports = [{
    "picture": {
      "url": 'http://www.dsaidemo.com/vehiclePictures/Wrangler Unlimited.jpg',
      "cdn_url": 'http://www.dsaidemo.com/vehiclePictures/Wrangler Unlimited.jpg'
    },
    "car_value": 10,
    "VEHICLE_ID": "400887177",
    "YEAR": "2015",
    "MAKE": "Jeep",
    "MODEL": "Wrangler Unlimited",
    "TRIM": "Sport RHD",
    "STYLE": "4x4 Sport RHD 4dr SUV",
    "VEHICLE_TYPE": "SUV",
    "BODY_TYPE": 0.0,
    "BODY_SUBTYPE": null,
    "OEM_BODY_STYLE": 0.0,
    "DOORS": "4",
    "OEM_DOORS": "4",
    "MSRP": "31295",
    "PLANT": "Toledo, Ohio",
    "RESTRAINT_TYPE": "Driver and Passenger Front Airbags and Passenger Deactivation Switch",
    "GVW_RANGE": "5001-6000",
    "LENGTH": "173.4",
    "HEIGHT": "70.8",
    "WIDTH": "82.8",
    "WHEELBASE": "116",
    "CURB_WEIGHT": "4075",
    "GROSS_VEHICLE_WEIGHT_RATING": "5400",
    "GROSS_COMBINED_WEIGHT_RATING": "0",
    "TMP_WHEEL_DIA": "16.0 x 7.0",
    "TMP_TANK1_GAL": "22.5",
    "MAX_PAYLOAD": 1000.0,
    "TONNAGE": "Compact",
    "WIDTH_NO_MIRRORS": "73.9",
    "LENGTH_NO_BUMPERS": "0",
    "DEF_ENGINE_ID": "300000957",
    "DRIVE_TYPE": "4X4",
    "FUEL_TYPE": "G",
    "DEF_ENGINE_BLOCK": "V",
    "DEF_ENGINE_CYLINDERS": "6",
    "DEF_ENGINE_SIZE": "3.6",
    "ENGINE_SIZE_UOM": "Li",
    "DEF_ENGINE_ASPIRATION": "N/A",
    "DEF_TRANS_ID": "222296",
    "DEF_TRANS_TYPE": "A",
    "DEF_TRANS_SPEEDS": "5"
  },
  {
    "picture": {
      "url": 'http://www.dsaidemo.com/vehiclePictures/Ram Pickup 1500.jpg',
      "cdn_url": 'http://www.dsaidemo.com/vehiclePictures/Ram Pickup 1500.jpg'
    },
    "car_value": 9,
    "VEHICLE_ID": "400889180",
    "YEAR": "2015",
    "MAKE": "Ram",
    "MODEL": "Ram Pickup 1500",
    "TRIM": "Big Horn",
    "STYLE": "4x2 Big Horn 4dr Quad Cab 6.3 ft. SB Pickup",
    "VEHICLE_TYPE": "Truck",
    "BODY_TYPE": 0.0,
    "BODY_SUBTYPE": 0.0,
    "OEM_BODY_STYLE": 0.0,
    "DOORS": "4",
    "OEM_DOORS": "4",
    "MSRP": "34495",
    "PLANT": "Saltillo, Mexico",
    "RESTRAINT_TYPE": "Driver and front passenger front and side impact airbags with occupant sensor, and front and rear side curtain airbags",
    "GVW_RANGE": "6001-7000",
    "LENGTH": "229",
    "HEIGHT": "77.9",
    "WIDTH": "79.4",
    "WHEELBASE": "140.5",
    "CURB_WEIGHT": "4905",
    "GROSS_VEHICLE_WEIGHT_RATING": "6800",
    "GROSS_COMBINED_WEIGHT_RATING": "9850",
    "TMP_WHEEL_DIA": "20.0 x 8.0",
    "TMP_TANK1_GAL": "26",
    "MAX_PAYLOAD": 1900.0,
    "TONNAGE": "42737.0",
    "WIDTH_NO_MIRRORS": "0",
    "LENGTH_NO_BUMPERS": "0",
    "DEF_ENGINE_ID": "300001083",
    "DRIVE_TYPE": "4X2",
    "FUEL_TYPE": "F",
    "DEF_ENGINE_BLOCK": "V",
    "DEF_ENGINE_CYLINDERS": "6",
    "DEF_ENGINE_SIZE": "3.6",
    "ENGINE_SIZE_UOM": "Li",
    "DEF_ENGINE_ASPIRATION": "N/A",
    "DEF_TRANS_ID": "255644",
    "DEF_TRANS_TYPE": "A",
    "DEF_TRANS_SPEEDS": "8"
  },
  {
    "picture": {
      "url": 'http://www.dsaidemo.com/vehiclePictures/Ram Pickup 1500.jpg',
      "cdn_url": 'http://www.dsaidemo.com/vehiclePictures/Ram Pickup 1500.jpg'
    },
    "car_value": 8,
    "VEHICLE_ID": "400889212",
    "YEAR": "2015",
    "MAKE": "Ram",
    "MODEL": "Ram Pickup 1500",
    "TRIM": "Lone Star",
    "STYLE": "4x2 Lone Star 4dr Quad Cab 6.3 ft. SB Pickup",
    "VEHICLE_TYPE": "Truck",
    "BODY_TYPE": 0.0,
    "BODY_SUBTYPE": 0.0,
    "OEM_BODY_STYLE": 0.0,
    "DOORS": "4",
    "OEM_DOORS": "4",
    "MSRP": "34495",
    "PLANT": "Saltillo, Mexico",
    "RESTRAINT_TYPE": "Driver and front passenger front and side impact airbags with occupant sensor, and front and rear side curtain airbags",
    "GVW_RANGE": "6001-7000",
    "LENGTH": "229",
    "HEIGHT": "77.9",
    "WIDTH": "79.4",
    "WHEELBASE": "140.5",
    "CURB_WEIGHT": "4905",
    "GROSS_VEHICLE_WEIGHT_RATING": "6800",
    "GROSS_COMBINED_WEIGHT_RATING": "9850",
    "TMP_WHEEL_DIA": "20.0 x 8.0",
    "TMP_TANK1_GAL": "26",
    "MAX_PAYLOAD": 1900.0,
    "TONNAGE": "42737.0",
    "WIDTH_NO_MIRRORS": "0",
    "LENGTH_NO_BUMPERS": "0",
    "DEF_ENGINE_ID": "300001083",
    "DRIVE_TYPE": "4X2",
    "FUEL_TYPE": "F",
    "DEF_ENGINE_BLOCK": "V",
    "DEF_ENGINE_CYLINDERS": "6",
    "DEF_ENGINE_SIZE": "3.6",
    "ENGINE_SIZE_UOM": "Li",
    "DEF_ENGINE_ASPIRATION": "N/A",
    "DEF_TRANS_ID": "255644",
    "DEF_TRANS_TYPE": "A",
    "DEF_TRANS_SPEEDS": "8"
  },
  {
    "picture": {
      "url": 'http://www.dsaidemo.com/vehiclePictures/Ram Pickup 1500.jpg',
      "cdn_url": 'http://www.dsaidemo.com/vehiclePictures/Ram Pickup 1500.jpg'
    },
    "car_value": 7,
    "VEHICLE_ID": "400889233",
    "YEAR": "2015",
    "MAKE": "Ram",
    "MODEL": "Ram Pickup 1500",
    "TRIM": "SLT",
    "STYLE": "4x2 SLT 4dr Quad Cab 6.3 ft. SB Pickup",
    "VEHICLE_TYPE": "Truck",
    "BODY_TYPE": 0.0,
    "BODY_SUBTYPE": 0.0,
    "OEM_BODY_STYLE": 0.0,
    "DOORS": "4",
    "OEM_DOORS": "4",
    "MSRP": "33290",
    "PLANT": "Saltillo, Mexico",
    "RESTRAINT_TYPE": "Driver and front passenger front and side impact airbags with occupant sensor, and front and rear side curtain airbags",
    "GVW_RANGE": "6001-7000",
    "LENGTH": "229",
    "HEIGHT": "77.2",
    "WIDTH": "79.4",
    "WHEELBASE": "140.5",
    "CURB_WEIGHT": "4905",
    "GROSS_VEHICLE_WEIGHT_RATING": "6800",
    "GROSS_COMBINED_WEIGHT_RATING": "9850",
    "TMP_WHEEL_DIA": "17.0 x 7.0",
    "TMP_TANK1_GAL": "26",
    "MAX_PAYLOAD": 1900.0,
    "TONNAGE": "42737.0",
    "WIDTH_NO_MIRRORS": "0",
    "LENGTH_NO_BUMPERS": "0",
    "DEF_ENGINE_ID": "300001083",
    "DRIVE_TYPE": "4X2",
    "FUEL_TYPE": "F",
    "DEF_ENGINE_BLOCK": "V",
    "DEF_ENGINE_CYLINDERS": "6",
    "DEF_ENGINE_SIZE": "3.6",
    "ENGINE_SIZE_UOM": "Li",
    "DEF_ENGINE_ASPIRATION": "N/A",
    "DEF_TRANS_ID": "255644",
    "DEF_TRANS_TYPE": "A",
    "DEF_TRANS_SPEEDS": "8"
  },
  {
    "picture": {
      "url": 'http://www.dsaidemo.com/vehiclePictures/F-150.jpg',
      "cdn_url": 'http://www.dsaidemo.com/vehiclePictures/F-150.jpg'
    },
    "car_value": 8,
    "VEHICLE_ID": "400888307",
    "YEAR": "2015",
    "MAKE": "Ford",
    "MODEL": "F-150",
    "TRIM": "Lariat",
    "STYLE": "4x4 Lariat 4dr SuperCrew Styleside 5.5 ft. SB",
    "VEHICLE_TYPE": "Truck",
    "BODY_TYPE": 0.0,
    "BODY_SUBTYPE": 0.0,
    "OEM_BODY_STYLE": 0.0,
    "DOORS": "4",
    "OEM_DOORS": "4",
    "MSRP": "44465",
    "PLANT": "Dearborn, Michigan",
    "RESTRAINT_TYPE": "Driver and front passenger front and side impact airbags with occupant sensor, and front and rear side curtain airbags",
    "GVW_RANGE": "6001-7000",
    "LENGTH": "231.9",
    "HEIGHT": "76.9",
    "WIDTH": "96.8",
    "WHEELBASE": "145",
    "CURB_WEIGHT": "4806",
    "GROSS_VEHICLE_WEIGHT_RATING": "6500",
    "GROSS_COMBINED_WEIGHT_RATING": "12800",
    "TMP_WHEEL_DIA": "18.0",
    "TMP_TANK1_GAL": "36",
    "MAX_PAYLOAD": 1640.0,
    "TONNAGE": "42737.0",
    "WIDTH_NO_MIRRORS": "79.9",
    "LENGTH_NO_BUMPERS": "0",
    "DEF_ENGINE_ID": "300001696",
    "DRIVE_TYPE": "4X4",
    "FUEL_TYPE": "G",
    "DEF_ENGINE_BLOCK": "V",
    "DEF_ENGINE_CYLINDERS": "6",
    "DEF_ENGINE_SIZE": "2.7",
    "ENGINE_SIZE_UOM": "Li",
    "DEF_ENGINE_ASPIRATION": "T",
    "DEF_TRANS_ID": "230943",
    "DEF_TRANS_TYPE": "A",
    "DEF_TRANS_SPEEDS": "6"
  },
  {
    "picture": {
      "url": 'http://www.dsaidemo.com/vehiclePictures/F-150.jpg',
      "cdn_url": 'http://www.dsaidemo.com/vehiclePictures/F-150.jpg'
    },
    "car_value": 8,
    "VEHICLE_ID": "400888308",
    "YEAR": "2015",
    "MAKE": "Ford",
    "MODEL": "F-150",
    "TRIM": "XLT",
    "STYLE": "4x4 XLT 4dr SuperCrew Styleside 5.5 ft. SB",
    "VEHICLE_TYPE": "Truck",
    "BODY_TYPE": 0.0,
    "BODY_SUBTYPE": 0.0,
    "OEM_BODY_STYLE": 0.0,
    "DOORS": "4",
    "OEM_DOORS": "4",
    "MSRP": "39425",
    "PLANT": "Dearborn, Michigan",
    "RESTRAINT_TYPE": "Driver and front passenger front and side impact airbags with occupant sensor, and front and rear side curtain airbags",
    "GVW_RANGE": "6001-7000",
    "LENGTH": "231.9",
    "HEIGHT": "76.9",
    "WIDTH": "96.8",
    "WHEELBASE": "145",
    "CURB_WEIGHT": "4696",
    "GROSS_VEHICLE_WEIGHT_RATING": "6350",
    "GROSS_COMBINED_WEIGHT_RATING": "12200",
    "TMP_WHEEL_DIA": "17.0",
    "TMP_TANK1_GAL": "36",
    "MAX_PAYLOAD": 1600.0,
    "TONNAGE": "42737.0",
    "WIDTH_NO_MIRRORS": "79.9",
    "LENGTH_NO_BUMPERS": "0",
    "DEF_ENGINE_ID": "300001696",
    "DRIVE_TYPE": "4X4",
    "FUEL_TYPE": "G",
    "DEF_ENGINE_BLOCK": "V",
    "DEF_ENGINE_CYLINDERS": "6",
    "DEF_ENGINE_SIZE": "2.7",
    "ENGINE_SIZE_UOM": "Li",
    "DEF_ENGINE_ASPIRATION": "T",
    "DEF_TRANS_ID": "230943",
    "DEF_TRANS_TYPE": "A",
    "DEF_TRANS_SPEEDS": "6"
  },
  {
    "picture": {
      "url": 'http://www.dsaidemo.com/vehiclePictures/F-150.jpg',
      "cdn_url": 'http://www.dsaidemo.com/vehiclePictures/F-150.jpg'
    },
    "car_value": 5,
    "VEHICLE_ID": "400888309",
    "YEAR": "2015",
    "MAKE": "Ford",
    "MODEL": "F-150",
    "TRIM": "XL",
    "STYLE": "4x4 XL 4dr SuperCrew Styleside 5.5 ft. SB",
    "VEHICLE_TYPE": "Truck",
    "BODY_TYPE": 0.0,
    "BODY_SUBTYPE": 0.0,
    "OEM_BODY_STYLE": 0.0,
    "DOORS": "4",
    "OEM_DOORS": "4",
    "MSRP": "35445",
    "PLANT": "Dearborn, Michigan",
    "RESTRAINT_TYPE": "Driver and front passenger front and side impact airbags with occupant sensor, and front and rear side curtain airbags",
    "GVW_RANGE": "6001-7000",
    "LENGTH": "231.9",
    "HEIGHT": "76.9",
    "WIDTH": "96.8",
    "WHEELBASE": "145",
    "CURB_WEIGHT": "4696",
    "GROSS_VEHICLE_WEIGHT_RATING": "6350",
    "GROSS_COMBINED_WEIGHT_RATING": "12200",
    "TMP_WHEEL_DIA": "17.0",
    "TMP_TANK1_GAL": "36",
    "MAX_PAYLOAD": 1600.0,
    "TONNAGE": "42737.0",
    "WIDTH_NO_MIRRORS": "79.9",
    "LENGTH_NO_BUMPERS": "0",
    "DEF_ENGINE_ID": "300001696",
    "DRIVE_TYPE": "4X4",
    "FUEL_TYPE": "G",
    "DEF_ENGINE_BLOCK": "V",
    "DEF_ENGINE_CYLINDERS": "6",
    "DEF_ENGINE_SIZE": "2.7",
    "ENGINE_SIZE_UOM": "Li",
    "DEF_ENGINE_ASPIRATION": "T",
    "DEF_TRANS_ID": "230943",
    "DEF_TRANS_TYPE": "A",
    "DEF_TRANS_SPEEDS": "6"
  },
  {
    "picture": {
      "url": 'http://www.dsaidemo.com/vehiclePictures/Camaro.jpg',
      "cdn_url": 'http://www.dsaidemo.com/vehiclePictures/Camaro.jpg'
    },
    "car_value": 7,
    "VEHICLE_ID": "400886827",
    "YEAR": "2015",
    "MAKE": "Chevrolet",
    "MODEL": "Camaro",
    "TRIM": "LS",
    "STYLE": "LS 2dr Coupe w/1LS",
    "VEHICLE_TYPE": "Car",
    "BODY_TYPE": 0.0,
    "BODY_SUBTYPE": null,
    "OEM_BODY_STYLE": 0.0,
    "DOORS": "2",
    "OEM_DOORS": "2",
    "MSRP": "23705",
    "PLANT": "Oshawa #1, Ontario, Canada",
    "RESTRAINT_TYPE": "Driver and passenger front and side airbags with passenger airbag deactivation and front and rear side curtain airbags.",
    "GVW_RANGE": null,
    "LENGTH": "190.6",
    "HEIGHT": "54.2",
    "WIDTH": "0",
    "WHEELBASE": "112.3",
    "CURB_WEIGHT": "3719",
    "GROSS_VEHICLE_WEIGHT_RATING": "0",
    "GROSS_COMBINED_WEIGHT_RATING": "0",
    "TMP_WHEEL_DIA": "18.0 x 17.5",
    "TMP_TANK1_GAL": "19",
    "MAX_PAYLOAD": 0.0,
    "TONNAGE": null,
    "WIDTH_NO_MIRRORS": "75.5",
    "LENGTH_NO_BUMPERS": "0",
    "DEF_ENGINE_ID": "300000805",
    "DRIVE_TYPE": "RWD",
    "FUEL_TYPE": "G",
    "DEF_ENGINE_BLOCK": "V",
    "DEF_ENGINE_CYLINDERS": "6",
    "DEF_ENGINE_SIZE": "3.6",
    "ENGINE_SIZE_UOM": "Li",
    "DEF_ENGINE_ASPIRATION": "N/A",
    "DEF_TRANS_ID": "257691",
    "DEF_TRANS_TYPE": "M",
    "DEF_TRANS_SPEEDS": "6"
  },
  {
    "picture": {
      "url": 'http://www.dsaidemo.com/vehiclePictures/MAZDA3.jpg',
      "cdn_url": 'http://www.dsaidemo.com/vehiclePictures/MAZDA3.jpg'
    },
    "car_value": 8,
    "VEHICLE_ID": "400884424",
    "YEAR": "2014",
    "MAKE": "Mazda",
    "MODEL": "MAZDA3",
    "TRIM": "s Grand Touring",
    "STYLE": "s Grand Touring 4dr Sedan",
    "VEHICLE_TYPE": "Car",
    "BODY_TYPE": 0.0,
    "BODY_SUBTYPE": null,
    "OEM_BODY_STYLE": 0.0,
    "DOORS": "4",
    "OEM_DOORS": "4",
    "MSRP": "25995",
    "PLANT": "Hofu, Yamaguchi, Japan",
    "RESTRAINT_TYPE": "Driver and front passenger front airbags with occupant sensing deactivation, front side airbags and front and rear side curtain airbags with rollover sensor.",
    "GVW_RANGE": null,
    "LENGTH": "180.3",
    "HEIGHT": "57.3",
    "WIDTH": "0",
    "WHEELBASE": "106.3",
    "CURB_WEIGHT": "2982",
    "GROSS_VEHICLE_WEIGHT_RATING": "0",
    "GROSS_COMBINED_WEIGHT_RATING": "0",
    "TMP_WHEEL_DIA": "18.0 x 7.0",
    "TMP_TANK1_GAL": "13.2",
    "MAX_PAYLOAD": 0.0,
    "TONNAGE": null,
    "WIDTH_NO_MIRRORS": "70.7",
    "LENGTH_NO_BUMPERS": "0",
    "DEF_ENGINE_ID": "300001118",
    "DRIVE_TYPE": "FWD",
    "FUEL_TYPE": "G",
    "DEF_ENGINE_BLOCK": "I",
    "DEF_ENGINE_CYLINDERS": "4",
    "DEF_ENGINE_SIZE": "2.5",
    "ENGINE_SIZE_UOM": "Li",
    "DEF_ENGINE_ASPIRATION": "N/A",
    "DEF_TRANS_ID": "213347",
    "DEF_TRANS_TYPE": "A",
    "DEF_TRANS_SPEEDS": "6"
  },
  {
    "picture": {
      "url": 'http://www.dsaidemo.com/vehiclePictures/GT-R.jpg',
      "cdn_url": 'http://www.dsaidemo.com/vehiclePictures/GT-R.jpg'
    },
    "car_value": 6,
    "VEHICLE_ID": "400886231",
    "YEAR": "2015",
    "MAKE": "Nissan",
    "MODEL": "GT-R",
    "TRIM": "Premium",
    "STYLE": "AWD Premium 2dr Coupe",
    "VEHICLE_TYPE": "Car",
    "BODY_TYPE": 0.0,
    "BODY_SUBTYPE": null,
    "OEM_BODY_STYLE": 0.0,
    "DOORS": "2",
    "OEM_DOORS": "2",
    "MSRP": "101770",
    "PLANT": "Tochigi, Japan",
    "RESTRAINT_TYPE": "Driver and passenger front, side impact, and side curtain airbags with occupant sensing deactivation",
    "GVW_RANGE": "4001-5000",
    "LENGTH": "183.8",
    "HEIGHT": "53.9",
    "WIDTH": "74.6",
    "WHEELBASE": "109.4",
    "CURB_WEIGHT": "3851",
    "GROSS_VEHICLE_WEIGHT_RATING": "4669",
    "GROSS_COMBINED_WEIGHT_RATING": "0",
    "TMP_WHEEL_DIA": "20.0 x 9.5",
    "TMP_TANK1_GAL": "19.5",
    "MAX_PAYLOAD": 0.0,
    "TONNAGE": null,
    "WIDTH_NO_MIRRORS": "0",
    "LENGTH_NO_BUMPERS": "0",
    "DEF_ENGINE_ID": "300000909",
    "DRIVE_TYPE": "AWD",
    "FUEL_TYPE": "G",
    "DEF_ENGINE_BLOCK": "V",
    "DEF_ENGINE_CYLINDERS": "6",
    "DEF_ENGINE_SIZE": "3.8",
    "ENGINE_SIZE_UOM": "Li",
    "DEF_ENGINE_ASPIRATION": "TT",
    "DEF_TRANS_ID": "257720",
    "DEF_TRANS_TYPE": "A",
    "DEF_TRANS_SPEEDS": "6"
  },
  {
    "picture": {
      "url": 'http://www.dsaidemo.com/vehiclePictures/GT-R.jpg',
      "cdn_url": 'http://www.dsaidemo.com/vehiclePictures/GT-R.jpg'
    },
    "car_value": 6,
    "VEHICLE_ID": "400886232",
    "YEAR": "2015",
    "MAKE": "Nissan",
    "MODEL": "GT-R",
    "TRIM": "Black Edition",
    "STYLE": "AWD Black Edition 2dr Coupe",
    "VEHICLE_TYPE": "Car",
    "BODY_TYPE": 0.0,
    "BODY_SUBTYPE": null,
    "OEM_BODY_STYLE": 0.0,
    "DOORS": "2",
    "OEM_DOORS": "2",
    "MSRP": "111510",
    "PLANT": "Tochigi, Japan",
    "RESTRAINT_TYPE": "Driver and passenger front, side impact, and side curtain airbags with occupant sensing deactivation",
    "GVW_RANGE": "4001-5000",
    "LENGTH": "183.8",
    "HEIGHT": "53.9",
    "WIDTH": "74.6",
    "WHEELBASE": "109.4",
    "CURB_WEIGHT": "3831",
    "GROSS_VEHICLE_WEIGHT_RATING": "4669",
    "GROSS_COMBINED_WEIGHT_RATING": "0",
    "TMP_WHEEL_DIA": "20.0 x 9.5",
    "TMP_TANK1_GAL": "19.5",
    "MAX_PAYLOAD": 0.0,
    "TONNAGE": null,
    "WIDTH_NO_MIRRORS": "0",
    "LENGTH_NO_BUMPERS": "0",
    "DEF_ENGINE_ID": "300000909",
    "DRIVE_TYPE": "AWD",
    "FUEL_TYPE": "G",
    "DEF_ENGINE_BLOCK": "V",
    "DEF_ENGINE_CYLINDERS": "6",
    "DEF_ENGINE_SIZE": "3.8",
    "ENGINE_SIZE_UOM": "Li",
    "DEF_ENGINE_ASPIRATION": "TT",
    "DEF_TRANS_ID": "257720",
    "DEF_TRANS_TYPE": "A",
    "DEF_TRANS_SPEEDS": "6"
  },
  {
    "picture": {
      "url": 'http://www.dsaidemo.com/vehiclePictures/GT-R.jpg',
      "cdn_url": 'http://www.dsaidemo.com/vehiclePictures/GT-R.jpg'
    },
    "car_value": 6,
    "VEHICLE_ID": "400886483",
    "YEAR": "2015",
    "MAKE": "Nissan",
    "MODEL": "GT-R",
    "TRIM": "NISMO",
    "STYLE": "AWD NISMO 2dr Coupe",
    "VEHICLE_TYPE": "Car",
    "BODY_TYPE": 0.0,
    "BODY_SUBTYPE": null,
    "OEM_BODY_STYLE": 0.0,
    "DOORS": "2",
    "OEM_DOORS": "2",
    "MSRP": "149990",
    "PLANT": "Tochigi, Japan",
    "RESTRAINT_TYPE": "Driver and passenger front, side impact, and side curtain airbags with occupant sensing deactivation",
    "GVW_RANGE": "4001-5000",
    "LENGTH": "183.9",
    "HEIGHT": "53.9",
    "WIDTH": "74.6",
    "WHEELBASE": "109.4",
    "CURB_WEIGHT": "3851",
    "GROSS_VEHICLE_WEIGHT_RATING": "4669",
    "GROSS_COMBINED_WEIGHT_RATING": "0",
    "TMP_WHEEL_DIA": "20.0 x 9.5",
    "TMP_TANK1_GAL": "19.5",
    "MAX_PAYLOAD": 0.0,
    "TONNAGE": null,
    "WIDTH_NO_MIRRORS": "0",
    "LENGTH_NO_BUMPERS": "0",
    "DEF_ENGINE_ID": "300001418",
    "DRIVE_TYPE": "AWD",
    "FUEL_TYPE": "G",
    "DEF_ENGINE_BLOCK": "V",
    "DEF_ENGINE_CYLINDERS": "6",
    "DEF_ENGINE_SIZE": "3.8",
    "ENGINE_SIZE_UOM": "Li",
    "DEF_ENGINE_ASPIRATION": "TT",
    "DEF_TRANS_ID": "257720",
    "DEF_TRANS_TYPE": "A",
    "DEF_TRANS_SPEEDS": "6"
  }
]
